name: TeamSurvival
main: nmt.minecraft.TeamSurvival.TeamSurvivalPlugin
version: 0.4.1
permissions:
    teamsurvival.*:
        children:
            teamsurvival.team.create: true
            teamsurvival.team.disband: true
            teamsurvival.team.info: true
            teamsurvival.session.create: true
            teamsurvival.session.start: true
            teamsurvival.session.info: true
            teamsurvival.session.stop: true
            teamsurvival.session.advance: true
            teamsurvival.creator.new: true
            teamsurvival.creator.open: true
            teamsurvival.creator.close: true
            teamsurvival.creator.setshop: true
            teamsurvival.creator.addarena: true 
            teamsurvival.creator.addbossarena: true
        default: op
    teamsurvival.team.join:
      default: true
    teamsurvival.team.leave:
      default: true
commands:
    teamsurvival:
        permission: teamsurvival.*
        usage: /ts [session|team] {args}
        description: Container command for admin-level commands
        aliases: ts
    jointeam:
        permission: teamsurvival.team.join
        ussage: /jointeam [teamname]
        description: Joins a TeamSurvival team
        aliases: join
    leaveteam:
        permission: teamsurvival.team.leave
        ussage: /leaveteam
        description: Leaves a TeamSurvival team
        aliases: leave
    teamsurvivalcreator:
        permission: teamsurvival.creator.*
        usage: /tsc [open|close|setShop|setStartingLocation|addArena|setShopButton|info] {args}
        description: Container commmand for arena creation commands
        aliases: tsc
    
